package MMC;

public class Chemical {
    private String Chem;

    public Chemical(String chem){
        Chem = chem;
    }


    public double findMolarMass(){
        switch (Chem) {
            case "H":
                return 1.008;
            case "Li":
                return 6.94;
            case "Na":
                return 22.990;
            case "K":
                return 39.098;
            case "Rb":
                return 85.468;
            case "Cs":
                return 132.91;
            case "Fr":
                return 223;
            case "Be":
                return 9.0122;
            case "Mg":
                return 24.305;
            case "Ca":
                return 40.078;
            case "Sr":
                return 87.62;
            case "Ba":
                return 137.33;
            case "Ra":
                return 226;
            case "Sc":
                return 44.956;
            case "Y":
                return 88.9006;
            case "Ti":
                return 1.008;
            case "Zr":
                return 91.224;
            case "Hf":
                return 178.49;
            case "Rf":
                return 267;
            case "V":
                return 50.942;
            case "Nb":
                return 92.906;
            case "Ta":
                return 180.95;
            case "Db":
                return 269;
            case "Cr":
                return 51.996;
            case "Mo":
                return 95.95;
            case "W":
                return 183.84;
            case "Sg":
                return 269;
            case "Mn":
                return 54.938;
            case "Tc":
                return 98;
            case "Re":
                return 186.21;
            case "Bh":
                return 270;
            case "Fe":
                return 55.845;
            case "Ru":
                return 101.07;
            case "Os":
                return 190.23;
            case "Hs":
                return 277;
            case "Co":
                return 58.933;
            case "Rh":
                return 102.91;
            case "Ir":
                return 192.22;
            case "Mt":
                return 278;
            case "Ni":
                return 58.693;
            case "Pd":
                return 106.42;
            case "Pt":
                return 195.08;
            case "Ds":
                return 281;
            case "Cu":
                return 63.546;
            case "Ag":
                return 107.87;
            case "Au":
                return 196.97;
            case "Rg":
                return 282;
            case "Zn":
                return 65.38;
            case "Cd":
                return 112.41;
            case "Hg":
                return 200.59;
            case "Cn":
                return 285;
            case "B":
                return 10.81;
            case "Al":
                return 26.982;
            case "Ga":
                return 69.723;
            case "In":
                return 114.82;
            case "Tl":
                return 204.38;
            case "Nh":
                return 286;
            case "C":
                return 12.011;
            case "Si":
                return 28.085;
            case "Ge":
                return 72.630;
            case "Sn":
                return 118.71;
            case "Pb":
                return 207.2;
            case "Fl":
                return 289;
            case "N":
                return 14.007;
            case "P":
                return 30.974;
            case "As":
                return 74.922;
            case "Sb":
                return 121.76;
            case "Bi":
                return 208.98;
            case "Mc":
                return 290;
            case "O":
                return 15.999;
            case "S":
                return 32.06;
            case "Se":
                return 78.971;
            case "Te":
                return 127.60;
            case "Po":
                return 209;
            case "Lv":
                return 293;
            case "F":
                return 18.998;
            case "Cl":
                return 35.45;
            case "Br":
                return 79.904;
            case "I":
                return 126.90;
            case "At":
                return 210;
            case "Ts":
                return 294;
            case "He":
                return 4.0026;
            case "Ne":
                return 20.180;
            case "Ar":
                return 39.948;
            case "Kr":
                return 83.798;
            case "Xe":
                return 131.29;
            case "Rn":
                return 222;
            case "Og":
                return 294;
            case "La":
                return 138.91;
            case "Ce":
                return 140.12;
            case "Pr":
                return 140.91;
            case "Nd":
                return 144.24;
            case "Pm":
                return 145;
            case "Sm":
                return 150.36;
            case "Eu":
                return 151.96;
            case "Gd":
                return 157.25;
            case "Tb":
                return 158.93;
            case "Dy":
                return 162.50;
            case "Ho":
                return 164.93;
            case "Er":
                return 167.26;
            case "Tm":
                return 169.93;
            case "Yb":
                return 173.05;
            case "Lu":
                return 174.97;
            case "Ac":
                return 227;
            case "Th":
                return 232.04;
            case "Pa":
                return 231.04;
            case "U":
                return 238.03;
            case "Np":
                return 237;
            case "Pu":
                return 244;
            case "Am":
                return 243;
            case "Cm":
                return 247;
            case "Bk":
                return 247;
            case "Cf":
                return 251;
            case "Es":
                return 252;
            case "Fm":
                return 257;
            case "Md":
                return 258;
            case "No":
                return 259;
            case "Lr":
                return 266;
            default:
                return 0;
        }
    }

    public boolean checkIfMultipleLetters(){
        switch (Chem){
            case "H":
            case "h":
            case "K":
            case "k":
            case "Y":
            case "y":
            case "V":
            case "v":
            case "W":
            case "w":
            case "B":
            case "b":
            case "C":
            case "c":
            case "N":
            case "n":
            case "P":
            case "p":
            case "O":
            case "o":
            case "S":
            case "s":
            case "F":
            case "f":
            case "I":
            case "i":
            case "U":
            case "u":
                return false;
        }
        return true;
    }
}